In [2]:
'''
Machine Learning(ML) python packages majorly divided into two categories

1. Data Analysis packages
    a. NumPy
    b. Pandas
    c. Matplotlib
    d. SciPy

2. Core ML packages (Next Notebooks)
'''

'\nMachine Learning(ML) python packages majorly divided into two categories\n\n1. Data Analysis packages\n    a. NumPy\n    b. Pandas\n    c. Matplotlib\n    d. SciPy\n\n2. Core ML packages\n    a. \n'

In [2]:
#NumPy - Arrays
import numpy as np
a1 = np.array([1,2,3]) #Rank 1 array

print(type(a1))
print(a1.shape)

print(a1[1])
a1[2] = 4
print(a1)

<class 'numpy.ndarray'>
(3,)
2
[1 2 4]


In [10]:
# Rank 2 array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

print(type(a2))
print(a2.shape)

print(a2[1][2])

[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>
6


In [13]:
# Built in funcitons to initialize NumPy arrays

x = np.zeros((3,3))
print(x)

y = np.ones((4,4))
print(y)

z = np.full((2,2),7) #Constant array
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]


In [16]:
p = np.random.random((3,3))
print(p)

q = np.eye(4)
print(q)

[[0.56743025 0.71811584 0.10701614]
 [0.10030875 0.14634036 0.22627481]
 [0.27907167 0.4148253  0.62838153]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
r = np.arange(15)
print(r)

s = np.arange(5,10)
print(s)

t = np.arange(15,30, dtype=np.float)
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[5 6 7 8 9]
[15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]


In [29]:
mix = np.array([[1,2,3],[4,5.0,6],[7.+1.j,8,9+2.j]])
print(mix)

equiSpaceArray = np.linspace(0,5,11)
print(equiSpaceArray)

indicesArray = np.indices((3,3))
print(indicesArray)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+1.j 8.+0.j 9.+2.j]]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [38]:
#Array field access
fa = np.zeros((3,3),  dtype=[('a', np.int32),('b', np.float64, (3,3))])
#print(fa)
print(fa[2:])
#print(fa[:1])
print(fa['a'].shape, fa['a'].dtype)

[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]
(3, 3) int32


In [46]:
#Slicing
sl = np.array([1,2,3,4,5,6,7])
print(sl[2:8:3])
print(sl[-1:3:-1])

[3 6]
[7 6 5]


In [50]:
ab = np.array([[[1],[2],[3]],[[4],[5],[6]]])
print(ab.shape)
print(ab[1][1].ndim)

(2, 3, 1)
1


In [57]:
r2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(r2.dtype)
print(r2.shape)

int32
(3, 4)


In [5]:
#Matrix operations
m = np.array([[1,2],[3,4]])
print(m)
print(np.sum(m)) #sum of all elements
print(np.sum(m, axis=0)) # sum of column elements
print(np.sum(m, axis=1)) # sum of row elements
print(m.T) #transpose of a matrix

[[1 2]
 [3 4]]
10
[4 6]
[3 7]
[[1 3]
 [2 4]]


In [16]:
#Broad casting

m1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
v1 = np.array([1,0,1])

e1 = np.empty_like(m1)
print(e1)

print(m1+v1)

for i in range(3):
    e1[i:] = m1[i:] + v1
print(e1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [13]:
t = np.tile(v1, (3,1))
print(t)

print(e1+t)

[[1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 3  2  5]
 [ 6  5  8]
 [ 9  8 11]]


In [18]:
#Reshape
x1 = np.array([1,2,3])
print(x1)
print(x1.shape)

x2 = np.array([4,5])
print(x2.shape)

x1_ = np.reshape(x1, (3,1))
print(x1_)
print(x1_.shape)


[1 2 3]
(3,)
(2,)
[[1]
 [2]
 [3]]
(3, 1)


In [21]:
y1 = np.array([1,2,3,4])
y2 = np.reshape(y1, (2,2))
print(y2)

[[1 2]
 [3 4]]


In [22]:
#Pandas Datastructures - Series and DataFrame
import pandas as pd
s1 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s1)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [29]:
#Data frame
data = {'Gender': ['F', 'M', 'M'],'Emp_ID': ['E01', 'E02', 'E03'], 'Age': [25, 27, 25]}
df = pd.DataFrame(data, columns=['Gender', 'Emp_ID', 'Age'])

print(df)

  Gender Emp_ID  Age
0      F    E01   25
1      M    E02   27
2      M    E03   25


In [38]:
#File data loading
csv = pd.read_csv('data/food-price-index-november-2018-csv/food-price-index-nov18-index-numbers-csv-tables.csv')
excel = pd.read_excel('data/rss_contextures/rss_contextures.xlsx', 'YouTube')
excel_file = pd.ExcelFile('data/rss_contextures/rss_contextures.xlsx')

df_csv = pd.DataFrame(csv)
df_excel = pd.DataFrame(excel)

print(df_csv.shape)
print(df_excel.shape)
print(excel_file)

(10722, 8)
(27, 8)


In [39]:
#Basic Statistics
df_csv.describe()

Period    Data_value
count  10722.000000  10722.000000
mean    2004.096929    780.492127
std       11.169757    233.448895
min     1960.010000     45.116296
25%     1999.120000    662.199980
50%     2006.110000    804.101608
75%     2012.110000    975.037822
max     2018.110000   1199.233716

In [44]:
# Covariance tells us wheahter +ve / -ve ly related
df_csv.cov()
#print(df_csv.cov(min_periods=150))

Period    Data_value
Period       124.763480   2396.167889
Data_value  2396.167889  54498.386748

In [45]:
#Correlation
df_csv.corr()

Period  Data_value
Period      1.000000    0.918928
Data_value  0.918928    1.000000

In [46]:
#Viewin data
df_csv.head(2)

Series_reference   Period  Data_value STATUS  UNITS  \
0       CPIM.SE901  1960.01   45.923461  FINAL  Index   
1       CPIM.SE901  1960.02   45.498637  FINAL  Index   

                       Subject                             Group  \
0  Consumers Price Index - CPI  Food Price Index for New Zealand   
1  Consumers Price Index - CPI  Food Price Index for New Zealand   

  Series_title_1  
0           Food  
1           Food

In [47]:
df_csv.tail()

Series_reference   Period  Data_value STATUS  UNITS  \
10717    CPIM.SE901502  2018.07      1036.0  FINAL  Index   
10718    CPIM.SE901502  2018.08      1037.0  FINAL  Index   
10719    CPIM.SE901502  2018.09      1040.0  FINAL  Index   
10720    CPIM.SE901502  2018.10      1041.0  FINAL  Index   
10721    CPIM.SE901502  2018.11      1042.0  FINAL  Index   

                           Subject  \
10717  Consumers Price Index - CPI   
10718  Consumers Price Index - CPI   
10719  Consumers Price Index - CPI   
10720  Consumers Price Index - CPI   
10721  Consumers Price Index - CPI   

                                                  Group     Series_title_1  
10717  Food Price Index Level 3 Classes for New Zealand  Ready-to-eat food  
10718  Food Price Index Level 3 Classes for New Zealand  Ready-to-eat food  
10719  Food Price Index Level 3 Classes for New Zealand  Ready-to-eat food  
10720  Food Price Index Level 3 Classes for New Zealand  Ready-to-eat food  
10721  Food Price Index Level 3 Classes for New Zealand  Ready-to-eat food

In [49]:
df_csv.columns

Index(['Series_reference', 'Period', 'Data_value', 'STATUS', 'UNITS',
       'Subject', 'Group', 'Series_title_1'],
      dtype='object')

In [50]:
df_csv.dtypes

Series_reference     object
Period              float64
Data_value          float64
STATUS               object
UNITS                object
Subject              object
Group                object
Series_title_1       object
dtype: object

In [51]:
df_csv.values

array([['CPIM.SE901', 1960.01, 45.923460999999996, ...,
        'Consumers Price Index - CPI',
        'Food Price Index for New Zealand', 'Food'],
       ['CPIM.SE901', 1960.02, 45.498637, ...,
        'Consumers Price Index - CPI',
        'Food Price Index for New Zealand', 'Food'],
       ['CPIM.SE901', 1960.03, 45.116296000000006, ...,
        'Consumers Price Index - CPI',
        'Food Price Index for New Zealand', 'Food'],
       ...,
       ['CPIM.SE901502', 2018.09, 1040.0, ...,
        'Consumers Price Index - CPI',
        'Food Price Index Level 3 Classes for New Zealand',
        'Ready-to-eat food'],
       ['CPIM.SE901502', 2018.1, 1041.0, ...,
        'Consumers Price Index - CPI',
        'Food Price Index Level 3 Classes for New Zealand',
        'Ready-to-eat food'],
       ['CPIM.SE901502', 2018.11, 1042.0, ...,
        'Consumers Price Index - CPI',
        'Food Price Index Level 3 Classes for New Zealand',
        'Ready-to-eat food']], dtype=object)

In [52]:
df_csv.index

RangeIndex(start=0, stop=10722, step=1)

In [54]:
df_csv['Group'].unique()

array(['Food Price Index for New Zealand',
       'Food Price Index Level 2 Subgroups for New Zealand',
       'Food Price Index Level 3 Classes for New Zealand',
       'Food Price Index Level 4 Sections for New Zealand'], dtype=object)

In [73]:
df_m = df_csv.sort_values(['Group','Period'], ascending=[True, False])
print(df_m.shape)

df_m[0:4] # rows

(10722, 8)


Series_reference   Period  Data_value STATUS  UNITS  \
940       CPIM.SE9011  2018.11       824.0  FINAL  Index   
2043      CPIM.SE9012  2018.11      1018.0  FINAL  Index   
4905      CPIM.SE9013  2018.11      1012.0  FINAL  Index   
9306      CPIM.SE9014  2018.11      1012.0  FINAL  Index   

                          Subject  \
940   Consumers Price Index - CPI   
2043  Consumers Price Index - CPI   
4905  Consumers Price Index - CPI   
9306  Consumers Price Index - CPI   

                                                  Group  \
940   Food Price Index Level 2 Subgroups for New Zea...   
2043  Food Price Index Level 2 Subgroups for New Zea...   
4905  Food Price Index Level 2 Subgroups for New Zea...   
9306  Food Price Index Level 2 Subgroups for New Zea...   

               Series_title_1  
940      Fruit and vegetables  
2043   Meat, poultry and fish  
4905             Grocery food  
9306  Non-alcoholic beverages

In [75]:
df_m.loc[1:6] #By Index

Empty DataFrame
Columns: [Series_reference, Period, Data_value, STATUS, UNITS, Subject, Group, Series_title_1]
Index: []

In [76]:
df_m[['Group','Period']]

Group   Period
940    Food Price Index Level 2 Subgroups for New Zea...  2018.11
2043   Food Price Index Level 2 Subgroups for New Zea...  2018.11
4905   Food Price Index Level 2 Subgroups for New Zea...  2018.11
9306   Food Price Index Level 2 Subgroups for New Zea...  2018.11
10008  Food Price Index Level 2 Subgroups for New Zea...  2018.11
939    Food Price Index Level 2 Subgroups for New Zea...  2018.10
2042   Food Price Index Level 2 Subgroups for New Zea...  2018.10
4904   Food Price Index Level 2 Subgroups for New Zea...  2018.10
9305   Food Price Index Level 2 Subgroups for New Zea...  2018.10
10007  Food Price Index Level 2 Subgroups for New Zea...  2018.10
938    Food Price Index Level 2 Subgroups for New Zea...  2018.09
2041   Food Price Index Level 2 Subgroups for New Zea...  2018.09
4903   Food Price Index Level 2 Subgroups for New Zea...  2018.09
9304   Food Price Index Level 2 Subgroups for New Zea...  2018.09
10006  Food Price Index Level 2 Subgroups for New Zea...  2018.09
937    Food Price Index Level 2 Subgroups for New Zea...  2018.08
2040   Food Price Index Level 2 Subgroups for New Zea...  2018.08
4902   Food Price Index Level 2 Subgroups for New Zea...  2018.08
9303   Food Price Index Level 2 Subgroups for New Zea...  2018.08
10005  Food Price Index Level 2 Subgroups for New Zea...  2018.08
936    Food Price Index Level 2 Subgroups for New Zea...  2018.07
2039   Food Price Index Level 2 Subgroups for New Zea...  2018.07
4901   Food Price Index Level 2 Subgroups for New Zea...  2018.07
9302   Food Price Index Level 2 Subgroups for New Zea...  2018.07
10004  Food Price Index Level 2 Subgroups for New Zea...  2018.07
935    Food Price Index Level 2 Subgroups for New Zea...  2018.06
2038   Food Price Index Level 2 Subgroups for New Zea...  2018.06
4900   Food Price Index Level 2 Subgroups for New Zea...  2018.06
9301   Food Price Index Level 2 Subgroups for New Zea...  2018.06
10003  Food Price Index Level 2 Subgroups for New Zea...  2018.06
...                                                  ...      ...
29                      Food Price Index for New Zealand  1962.06
28                      Food Price Index for New Zealand  1962.05
27                      Food Price Index for New Zealand  1962.04
26                      Food Price Index for New Zealand  1962.03
25                      Food Price Index for New Zealand  1962.02
24                      Food Price Index for New Zealand  1962.01
23                      Food Price Index for New Zealand  1961.12
22                      Food Price Index for New Zealand  1961.11
21                      Food Price Index for New Zealand  1961.10
20                      Food Price Index for New Zealand  1961.09
19                      Food Price Index for New Zealand  1961.08
18                      Food Price Index for New Zealand  1961.07
17                      Food Price Index for New Zealand  1961.06
16                      Food Price Index for New Zealand  1961.05
15                      Food Price Index for New Zealand  1961.04
14                      Food Price Index for New Zealand  1961.03
13                      Food Price Index for New Zealand  1961.02
12                      Food Price Index for New Zealand  1961.01
11                      Food Price Index for New Zealand  1960.12
10                      Food Price Index for New Zealand  1960.11
9                       Food Price Index for New Zealand  1960.10
8                       Food Price Index for New Zealand  1960.09
7                       Food Price Index for New Zealand  1960.08
6                       Food Price Index for New Zealand  1960.07
5                       Food Price Index for New Zealand  1960.06
4                       Food Price Index for New Zealand  1960.05
3                       Food Price Index for New Zealand  1960.04
2                       Food Price Index for New Zealand  1960.03
1                       Food Price Index for New Zealand  1960.02
0                       F

In [82]:
df_m[df_m['Data_value'] > 500] #Filtering

Series_reference   Period   Data_value STATUS  UNITS  \
940        CPIM.SE9011  2018.11   824.000000  FINAL  Index   
2043       CPIM.SE9012  2018.11  1018.000000  FINAL  Index   
4905       CPIM.SE9013  2018.11  1012.000000  FINAL  Index   
9306       CPIM.SE9014  2018.11  1012.000000  FINAL  Index   
10008      CPIM.SE9015  2018.11  1040.000000  FINAL  Index   
939        CPIM.SE9011  2018.10   855.000000  FINAL  Index   
2042       CPIM.SE9012  2018.10  1022.000000  FINAL  Index   
4904       CPIM.SE9013  2018.10  1012.000000  FINAL  Index   
9305       CPIM.SE9014  2018.10  1024.000000  FINAL  Index   
10007      CPIM.SE9015  2018.10  1038.000000  FINAL  Index   
938        CPIM.SE9011  2018.09   904.000000  FINAL  Index   
2041       CPIM.SE9012  2018.09   998.000000  FINAL  Index   
4903       CPIM.SE9013  2018.09  1016.000000  FINAL  Index   
9304       CPIM.SE9014  2018.09  1027.000000  FINAL  Index   
10006      CPIM.SE9015  2018.09  1037.000000  FINAL  Index   
937        CPIM.SE9011  2018.08   956.000000  FINAL  Index   
2040       CPIM.SE9012  2018.08   981.000000  FINAL  Index   
4902       CPIM.SE9013  2018.08  1007.000000  FINAL  Index   
9303       CPIM.SE9014  2018.08  1023.000000  FINAL  Index   
10005      CPIM.SE9015  2018.08  1035.000000  FINAL  Index   
936        CPIM.SE9011  2018.07   977.000000  FINAL  Index   
2039       CPIM.SE9012  2018.07   995.000000  FINAL  Index   
4901       CPIM.SE9013  2018.07  1002.000000  FINAL  Index   
9302       CPIM.SE9014  2018.07  1043.000000  FINAL  Index   
10004      CPIM.SE9015  2018.07  1034.000000  FINAL  Index   
935        CPIM.SE9011  2018.06   954.000000  FINAL  Index   
2038       CPIM.SE9012  2018.06   994.000000  FINAL  Index   
4900       CPIM.SE9013  2018.06   999.000000  FINAL  Index   
9301       CPIM.SE9014  2018.06  1025.000000  FINAL  Index   
10003      CPIM.SE9015  2018.06  1030.000000  FINAL  Index   
...                ...      ...          ...    ...    ...   
373         CPIM.SE901  1991.02   582.883262  FINAL  Index   
372         CPIM.SE901  1991.01   585.417537  FINAL  Index   
371         CPIM.SE901  1990.12   582.376406  FINAL  Index   
370         CPIM.SE901  1990.11   583.896972  FINAL  Index   
369         CPIM.SE901  1990.10   584.910682  FINAL  Index   
368         CPIM.SE901  1990.09   588.965522  FINAL  Index   
367         CPIM.SE901  1990.08   583.390117  FINAL  Index   
366         CPIM.SE901  1990.07   580.348986  FINAL  Index   
365         CPIM.SE901  1990.06   579.842131  FINAL  Index   
364         CPIM.SE901  1990.05   576.801002  FINAL  Index   
363         CPIM.SE901  1990.04   573.759872  FINAL  Index   
362         CPIM.SE901  1990.03   568.184467  FINAL  Index   
361         CPIM.SE901  1990.02   563.115916  FINAL  Index   
360         CPIM.SE901  1990.01   563.622771  FINAL  Index   
359         CPIM.SE901  1989.12   563.622771  FINAL  Index   
358         CPIM.SE901  1989.11   565.650191  FINAL  Index   
357         CPIM.SE901  1989.10   566.157046  FINAL  Index   
356         CPIM.SE901  1989.09   563.115916  FINAL  Index   
355         CPIM.SE901  1989.08   556.019946  FINAL  Index   
354         CPIM.SE901  1989.07   547.403411  FINAL  Index   
353         CPIM.SE901  1989.06   527.129211  FINAL  Index   
352         CPIM.SE901  1989.05   521.046950  FINAL  Index   
351         CPIM.SE901  1989.04   514.964690  FINAL  Index   
350         CPIM.SE901  1989.03   511.923560  FINAL  Index   
349         CPIM.SE901  1989.02   512.430415  FINAL  Index   
348         CPIM.SE901  1989.01   504.320735  FINAL  Index   
347         CPIM.SE901  1988.12   506.855010  FINAL  Index   
346         CPIM.SE901  1988.11   508.408827  FINAL  Index   
345         CPIM.SE901  1988.10   506.855010  FINAL  Index   
344         CPIM.SE901  1988.09   500.950507  FINAL  Index   

                           Subject  \
940    Consumers Price Index - CPI   
2043   Consumers Price Index - CPI   
4905   Consumers Price Index - CPI   
9306   Co

In [84]:
df_m[df_m['Group'] == "Food Price Index for New Zealand"] #Filtering

Series_reference   Period   Data_value STATUS  UNITS  \
706       CPIM.SE901  2018.11   991.000000  FINAL  Index   
705       CPIM.SE901  2018.10   997.000000  FINAL  Index   
704       CPIM.SE901  2018.09  1003.000000  FINAL  Index   
703       CPIM.SE901  2018.08  1004.000000  FINAL  Index   
702       CPIM.SE901  2018.07  1009.000000  FINAL  Index   
701       CPIM.SE901  2018.06  1002.000000  FINAL  Index   
700       CPIM.SE901  2018.05   997.000000  FINAL  Index   
699       CPIM.SE901  2018.04   997.000000  FINAL  Index   
698       CPIM.SE901  2018.03   996.000000  FINAL  Index   
697       CPIM.SE901  2018.02   986.000000  FINAL  Index   
696       CPIM.SE901  2018.01   991.000000  FINAL  Index   
695       CPIM.SE901  2017.12   978.851964  FINAL  Index   
694       CPIM.SE901  2017.11   987.160121  FINAL  Index   
693       CPIM.SE901  2017.10   990.936556  FINAL  Index   
692       CPIM.SE901  2017.09  1002.265861  FINAL  Index   
691       CPIM.SE901  2017.08  1004.531722  FINAL  Index   
690       CPIM.SE901  2017.07   998.489426  FINAL  Index   
689       CPIM.SE901  2017.06  1000.000000  FINAL  Index   
688       CPIM.SE901  2017.05   997.734139  FINAL  Index   
687       CPIM.SE901  2017.04   974.320242  FINAL  Index   
686       CPIM.SE901  2017.03   981.873112  FINAL  Index   
685       CPIM.SE901  2017.02   984.894260  FINAL  Index   
684       CPIM.SE901  2017.01   983.383686  FINAL  Index   
683       CPIM.SE901  2016.12   956.948640  FINAL  Index   
682       CPIM.SE901  2016.11   964.501511  FINAL  Index   
681       CPIM.SE901  2016.10   965.256798  FINAL  Index   
680       CPIM.SE901  2016.09   972.809668  FINAL  Index   
679       CPIM.SE901  2016.08   981.873112  FINAL  Index   
678       CPIM.SE901  2016.07   969.033233  FINAL  Index   
677       CPIM.SE901  2016.06   971.299094  FINAL  Index   
..               ...      ...          ...    ...    ...   
29        CPIM.SE901  1962.06    46.688144  FINAL  Index   
28        CPIM.SE901  1962.05    46.730627  FINAL  Index   
27        CPIM.SE901  1962.04    46.688144  FINAL  Index   
26        CPIM.SE901  1962.03    46.858074  FINAL  Index   
25        CPIM.SE901  1962.02    46.943039  FINAL  Index   
24        CPIM.SE901  1962.01    47.410345  FINAL  Index   
23        CPIM.SE901  1961.12    47.622757  FINAL  Index   
22        CPIM.SE901  1961.11    47.877651  FINAL  Index   
21        CPIM.SE901  1961.10    47.028004  FINAL  Index   
20        CPIM.SE901  1961.09    47.112968  FINAL  Index   
19        CPIM.SE901  1961.08    47.835169  FINAL  Index   
18        CPIM.SE901  1961.07    46.560697  FINAL  Index   
17        CPIM.SE901  1961.06    45.923461  FINAL  Index   
16        CPIM.SE901  1961.05    45.923461  FINAL  Index   
15        CPIM.SE901  1961.04    46.135873  FINAL  Index   
14        CPIM.SE901  1961.03    46.178356  FINAL  Index   
13        CPIM.SE901  1961.02    46.645662  FINAL  Index   
12        CPIM.SE901  1961.01    47.155451  FINAL  Index   
11        CPIM.SE901  1960.12    47.707722  FINAL  Index   
10        CPIM.SE901  1960.11    48.599852  FINAL  Index   
9         CPIM.SE901  1960.10    47.495310  FINAL  Index   
8         CPIM.SE901  1960.09    46.943039  FINAL  Index   
7         CPIM.SE901  1960.08    47.112968  FINAL  Index   
6         CPIM.SE901  1960.07    46.390767  FINAL  Index   
5         CPIM.SE901  1960.06    45.668567  FINAL  Index   
4         CPIM.SE901  1960.05    45.286226  FINAL  Index   
3         CPIM.SE901  1960.04    45.158779  FINAL  Index   
2         CPIM.SE901  1960.03    45.116296  FINAL  Index   
1         CPIM.SE901  1960.02    45.498637  FINAL  Index   
0         CPIM.SE901  1960.01    45.923461  FINAL  Index   

                         Subject                             Group  \
706  Consumers Price Index - CPI  Food Price Index for New Zealand   
705  Consumers Price Index - CPI  Food Price Index for New Zealand   
704  Consumers Price Index - CPI  Food Price Index for New Zealand   
703

In [105]:
df1 = pd.DataFrame(pd.Series(df_m['Period']).astype('str'))
print(df1['Period'].dtype)
#dt = pd.to_datetime(pd.Series(df_m['Period']))
#print(dt)

object


In [109]:
modified_df = df_m['Data_value'].map(lambda x: x+10000)
print(modified_df.tail(5))

4    10045.286226
3    10045.158779
2    10045.116296
1    10045.498637
0    10045.923461
Name: Data_value, dtype: float64


In [112]:
data = {'emp_id': ['1', '2', '3', '4', '5'], 
        'first_name': ['Jason', 'Andy', 'Allen', 'Alice', 'Amy'], 
        'last_name': ['Larkin', 'Jacob', 'A', 'AA', 'Jackson']}

df_1 = pd.DataFrame(data, columns = ['emp_id', 'first_name', 'last_name']) 

data2 = {'emp_id': ['4', '5', '6', '7'],
        'first_name': ['Brian', 'Shize', 'Kim', 'Jose'],
        'last_name': ['Alexander', 'Suma', 'Mike', 'G']} 

df_2 = pd.DataFrame(data2, columns = ['emp_id', 'first_name', 'last_name'])

df = pd.concat([df_1, df_2])
print(df)

  emp_id first_name  last_name
0      1      Jason     Larkin
1      2       Andy      Jacob
2      3      Allen          A
3      4      Alice         AA
4      5        Amy    Jackson
0      4      Brian  Alexander
1      5      Shize       Suma
2      6        Kim       Mike
3      7       Jose          G


In [114]:
df_a = df_2.append(df_1)
print(df_a)

  emp_id first_name  last_name
0      4      Brian  Alexander
1      5      Shize       Suma
2      6        Kim       Mike
3      7       Jose          G
0      1      Jason     Larkin
1      2       Andy      Jacob
2      3      Allen          A
3      4      Alice         AA
4      5        Amy    Jackson


In [115]:
df_c = pd.concat([df_1, df_2], axis=1)
print(df_c)

  emp_id first_name last_name emp_id first_name  last_name
0      1      Jason    Larkin      4      Brian  Alexander
1      2       Andy     Jacob      5      Shize       Suma
2      3      Allen         A      6        Kim       Mike
3      4      Alice        AA      7       Jose          G
4      5        Amy   Jackson    NaN        NaN        NaN


In [119]:
#Merging

df_merge = pd.merge(df_1, df_2, on='emp_id')
print(df_merge)

  emp_id first_name_x last_name_x first_name_y last_name_y
0      4        Alice          AA        Brian   Alexander
1      5          Amy     Jackson        Shize        Suma


In [120]:
df_mergeL = pd.merge(df_1, df_2, on='emp_id', how='left', suffixes=('_left_','_right_'))
print(df_mergeL)

  emp_id first_name_left_ last_name_left_ first_name_right_ last_name_right_
0      1            Jason          Larkin               NaN              NaN
1      2             Andy           Jacob               NaN              NaN
2      3            Allen               A               NaN              NaN
3      4            Alice              AA             Brian        Alexander
4      5              Amy         Jackson             Shize             Suma


In [133]:
#Grouping - groupBy
dfg = pd.DataFrame({
    'Name' : ['jack', 'jane', 'jack', 'jane', 'jack', 'jane', 'jack', 'jane'],
    'State' : ['SFO', 'SFO', 'NYK', 'CA', 'NYK', 'NYK', 'SFO', 'CA'],
    'Grade':['A','A','B','A','C','B','C','A'],
    'Age' : np.random.uniform(24, 50, size=8),
    'Salary' : np.random.uniform(3000, 5000, size=8)
})
print(dfg)
dfg.groupby(['State','Grade']).max()['Salary']

   Name State Grade        Age       Salary
0  jack   SFO     A  35.889513  4407.750707
1  jane   SFO     A  32.821189  3258.884518
2  jack   NYK     B  27.420181  3178.497386
3  jane    CA     A  39.643164  4997.408894
4  jack   NYK     C  33.126438  4902.738189
5  jane   NYK     B  49.081846  4176.835452
6  jack   SFO     C  43.200833  3154.956286
7  jane    CA     A  39.032799  3807.339769


State  Grade
CA     A        4997.408894
NYK    B        4176.835452
       C        4902.738189
SFO    A        4407.750707
       C        3154.956286
Name: Salary, dtype: float64

In [140]:
#Pivot Tables
piv = pd.pivot_table(dfg, values='Age', index=['State', 'Name'], columns=['Grade'])
print(piv.shape)
print('')
print(piv)
print('')

from IPython.display import display, HTML

display(piv)
print('')
display(HTML(piv.to_html()))

print('')
print(piv.to_html())

(5, 3)

Grade               A          B          C
State Name                                 
CA    jane  39.337981        NaN        NaN
NYK   jack        NaN  27.420181  33.126438
      jane        NaN  49.081846        NaN
SFO   jack  35.889513        NaN  43.200833
      jane  32.821189        NaN        NaN



Grade               A          B          C
State Name                                 
CA    jane  39.337981        NaN        NaN
NYK   jack        NaN  27.420181  33.126438
      jane        NaN  49.081846        NaN
SFO   jack  35.889513        NaN  43.200833
      jane  32.821189        NaN        NaN


<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Grade</th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
    </tr>
    <tr>
      <th>State</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>CA</th>
      <th>jane</th>
      <td>39.337981</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">NYK</th>
      <th>jack</th>
      <td>NaN</td>
      <td>27.420181</td>
      <td>33.126438</td>
    </tr>
    <tr>
      <th>jane</th>
      <td>NaN</td>
      <td>49.081846</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">SFO</th>
      <th>jack</th>
      <td>35.889513</td>
      <td>NaN</td>
      <td>43.200833</td>
    </tr>
    <tr>
      <th>jane</th>
      <td>32.821189</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
